#########################################################################################################

############################
#     PILATES SETTINGS     #
############################

# docker settings
docker_images:
  alpine: alpine:latest
